services:
  - type: web
    name: advanced-agent-interface
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_ENGINE_ID
        value: f60d7c389de5240cd
      - key: USE_ADVANCED_AGENT
        value: "true"
      - key: ENABLE_ENHANCED_ARXIV
        value: "true"
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: "."
