name: Build and Deploy Site

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Sync Documentation
        run: |
          python website/scripts/sync_docs.py
          git config --global user.name "Docs Bot"
          git config --global user.email "docs@example.com"
          git add -f website/docs/
          git commit -m "Update documentation" || echo "No docs changes"

      - name: Build site
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
