name: PR Tool Review
on:
  pull_request_target:
    types: [labeled]

jobs:
  review:
    # Only run the job if the newly added label is "run-tests"
    if: github.event.label.name == 'run-tests'
    runs-on: ubuntu-latest
    steps:
      - name: Check out base repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch fork code
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
          git checkout pr-${{ github.event.pull_request.number }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai pygithub python-dotenv

      - name: Run Integration Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ vars.OPENAI_BASE_URL }}
          OPENAI_MODEL_NAME: ${{ vars.OPENAI_MODEL_NAME }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
        run: |
          python .github/scripts/review_pr.py ${{ github.event.pull_request.number }}
