name: Weekly PyPI Release

on:
  schedule:
    - cron: '1 0 * * 1'  # Every Monday at 00:01 UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write  # Needed for creating tags and releases
      id-token: write  # Needed for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Generate version number
        run: |
          YEAR_WEEK=$(date +%y.%V)
          echo "PYPI_VERSION=0.$YEAR_WEEK" >> $GITHUB_ENV
          echo "RELEASE_TAG=v0.$YEAR_WEEK" >> $GITHUB_ENV

      - name: Update pyproject.toml version
        run: |
          sed -i "s/^version = .*/version = \"${PYPI_VERSION}\"/" pyproject.toml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Weekly version bump: ${PYPI_VERSION}"
          git push

      - name: Create Git tag
        run: |
          git tag -a ${RELEASE_TAG} -m "Weekly release ${RELEASE_TAG}"
          git push origin ${RELEASE_TAG}

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true

